#![allow(clippy::exhaustive_enums, reason = "Generated by sol! macro")]
#![allow(clippy::exhaustive_structs, reason = "Generated by sol! macro")]

use alloy::primitives::U256;
use alloy::sol;
use alloy::sol_types::SolCall;
use anyhow::{Context, Result};
use clap::{Args, Subcommand};
use polymarket_client_sdk_v2::types::Address;

use crate::auth;
use crate::output::OutputFormat;
use crate::output::approve::{ApprovalStatus, print_approval_status, print_tx_result};

use super::{
    COLLATERAL_SYMBOL, CONDITIONAL_TOKENS, CTF_COLLATERAL_ADAPTER, CTF_EXCHANGE, NEG_RISK_ADAPTER,
    NEG_RISK_CTF_COLLATERAL_ADAPTER, NEG_RISK_CTF_EXCHANGE, proxy,
};

sol! {
    #[sol(rpc)]
    interface IERC20 {
        function approve(address spender, uint256 value) external returns (bool);
        function allowance(address owner, address spender) external view returns (uint256);
    }

    #[sol(rpc)]
    interface IERC1155 {
        function setApprovalForAll(address operator, bool approved) external;
        function isApprovedForAll(address account, address operator) external view returns (bool);
    }
}

#[derive(Args)]
pub struct ApproveArgs {
    #[command(subcommand)]
    pub command: ApproveCommand,
}

#[derive(Subcommand)]
pub enum ApproveCommand {
    /// Check current contract approvals for a wallet
    Check {
        /// Wallet address to check (defaults to configured wallet)
        address: Option<Address>,
    },
    /// Approve all required contracts for trading (sends on-chain transactions)
    Set,
}

struct ApprovalTarget {
    name: &'static str,
    address: Address,
    needs_collateral_allowance: bool,
    needs_ctf_operator: bool,
}

struct PendingApproval {
    label: String,
    target: Address,
    calldata: Vec<u8>,
}

fn approval_targets() -> Result<Vec<ApprovalTarget>> {
    Ok(vec![
        ApprovalTarget {
            name: "CTF Exchange",
            address: CTF_EXCHANGE,
            needs_collateral_allowance: true,
            needs_ctf_operator: true,
        },
        ApprovalTarget {
            name: "Neg Risk Exchange",
            address: NEG_RISK_CTF_EXCHANGE,
            needs_collateral_allowance: true,
            needs_ctf_operator: true,
        },
        ApprovalTarget {
            name: "Neg Risk Adapter",
            address: NEG_RISK_ADAPTER,
            needs_collateral_allowance: true,
            needs_ctf_operator: true,
        },
        ApprovalTarget {
            name: "Conditional Tokens",
            address: CONDITIONAL_TOKENS,
            needs_collateral_allowance: true,
            needs_ctf_operator: false,
        },
        ApprovalTarget {
            name: "CTF Collateral Adapter",
            address: CTF_COLLATERAL_ADAPTER,
            needs_collateral_allowance: true,
            needs_ctf_operator: true,
        },
        ApprovalTarget {
            name: "Neg Risk CTF Collateral Adapter",
            address: NEG_RISK_CTF_COLLATERAL_ADAPTER,
            needs_collateral_allowance: true,
            needs_ctf_operator: true,
        },
    ])
}

fn collateral_is_approved(allowance: U256) -> bool {
    allowance > U256::ZERO
}

async fn resolve_owner(
    address_arg: Option<Address>,
    private_key: Option<&str>,
    signature_type: Option<&str>,
) -> Result<Address> {
    if let Some(addr) = address_arg {
        return Ok(addr);
    }
    match proxy::resolve_execution_mode(signature_type)? {
        proxy::ExecutionMode::Proxy => proxy::derive_proxy_address(private_key),
        proxy::ExecutionMode::DepositWallet => proxy::deposit_wallet_address(),
        proxy::ExecutionMode::Eoa => {
            let signer = auth::resolve_signer(private_key)?;
            Ok(polymarket_client_sdk_v2::auth::Signer::address(&signer))
        }
    }
}

async fn fetch_approval_statuses(
    owner: Address,
) -> Result<Vec<ApprovalStatus>> {
    let provider = auth::create_readonly_provider().await?;
    let collateral = IERC20::new(super::COLLATERAL_ADDRESS, provider.clone());
    let ctf = IERC1155::new(CONDITIONAL_TOKENS, provider.clone());

    let targets = approval_targets()?;
    let mut statuses = Vec::new();

    for target in &targets {
        let (collateral_allowance, collateral_error) = if target.needs_collateral_allowance {
            match collateral.allowance(owner, target.address).call().await {
                Ok(val) => (val, None),
                Err(e) => (U256::ZERO, Some(e.to_string())),
            }
        } else {
            (U256::ZERO, None)
        };

        let (ctf_approved, ctf_error) = if target.needs_ctf_operator {
            match ctf.isApprovedForAll(owner, target.address).call().await {
                Ok(val) => (Some(val), None),
                Err(e) => (Some(false), Some(e.to_string())),
            }
        } else {
            (None, None)
        };

        statuses.push(ApprovalStatus {
            contract_name: target.name.to_string(),
            contract_address: format!("{}", target.address),
            collateral_allowance,
            ctf_approved,
            collateral_error,
            ctf_error,
        });
    }

    Ok(statuses)
}

fn pending_approvals(statuses: &[ApprovalStatus]) -> Result<Vec<PendingApproval>> {
    let targets = approval_targets()?;
    let mut pending = Vec::new();

    for (target, status) in targets.iter().zip(statuses.iter()) {
        if target.needs_collateral_allowance
            && status.collateral_error.is_none()
            && !collateral_is_approved(status.collateral_allowance)
        {
            pending.push(PendingApproval {
                label: format!("{COLLATERAL_SYMBOL} \u{2192} {}", target.name),
                target: super::COLLATERAL_ADDRESS,
                calldata: IERC20::approveCall {
                    spender: target.address,
                    value: U256::MAX,
                }
                .abi_encode(),
            });
        }

        if target.needs_ctf_operator
            && status.ctf_error.is_none()
            && !status.ctf_approved.unwrap_or(false)
        {
            pending.push(PendingApproval {
                label: format!("CTF  \u{2192} {}", target.name),
                target: CONDITIONAL_TOKENS,
                calldata: IERC1155::setApprovalForAllCall {
                    operator: target.address,
                    approved: true,
                }
                .abi_encode(),
            });
        }
    }

    Ok(pending)
}

pub async fn execute(
    args: ApproveArgs,
    output: OutputFormat,
    private_key: Option<&str>,
    signature_type: Option<&str>,
) -> Result<()> {
    match args.command {
        ApproveCommand::Check { address } => {
            check(address, private_key, signature_type, output).await
        }
        ApproveCommand::Set => set(private_key, signature_type, output).await,
    }
}

async fn check(
    address_arg: Option<Address>,
    private_key: Option<&str>,
    signature_type: Option<&str>,
    output: OutputFormat,
) -> Result<()> {
    let owner = resolve_owner(address_arg, private_key, signature_type).await?;
    let statuses = fetch_approval_statuses(owner).await?;
    print_approval_status(&statuses, &output)
}

async fn set(
    private_key: Option<&str>,
    signature_type: Option<&str>,
    output: OutputFormat,
) -> Result<()> {
    let mode = proxy::resolve_execution_mode(signature_type)?;
    let owner = resolve_owner(None, private_key, signature_type).await?;
    let statuses = fetch_approval_statuses(owner).await?;
    let pending = pending_approvals(&statuses)?;

    if pending.is_empty() {
        match output {
            OutputFormat::Table => println!("All contracts already approved. You're ready to trade."),
            OutputFormat::Json => {
                println!("{}", serde_json::json!({"status": "already_approved"}));
            }
        }
        return Ok(());
    }

    if matches!(output, OutputFormat::Table) {
        println!("Approving contracts...\n");
    }

    let total = pending.len();
    let mut results: Vec<serde_json::Value> = Vec::new();

    if mode.allows_batch() && pending.len() > 1 {
        let labels: Vec<String> = pending.iter().map(|p| p.label.clone()).collect();
        let calls: Vec<(Address, Vec<u8>)> = pending
            .into_iter()
            .map(|p| (p.target, p.calldata))
            .collect();
        let (tx_hash, _, _) = proxy::send_calls(private_key, mode, calls)
            .await
            .context("Failed batched approval transaction")?;

        for (step, label) in labels.into_iter().enumerate() {
            match output {
                OutputFormat::Table => print_tx_result(step + 1, total, &label, tx_hash),
                OutputFormat::Json => results.push(serde_json::json!({
                    "step": step + 1,
                    "label": label,
                    "tx_hash": format!("{tx_hash}"),
                    "batched": true,
                })),
            }
        }
    } else {
        for (step, action) in pending.into_iter().enumerate() {
            let (tx_hash, _) =
                proxy::send_call(private_key, mode, action.target, action.calldata)
                    .await
                    .context(format!("Failed approval: {}", action.label))?;

            match output {
                OutputFormat::Table => print_tx_result(step + 1, total, &action.label, tx_hash),
                OutputFormat::Json => results.push(serde_json::json!({
                    "step": step + 1,
                    "label": action.label,
                    "tx_hash": format!("{tx_hash}"),
                    "batched": false,
                })),
            }
        }
    }

    match output {
        OutputFormat::Table => {
            println!("\nAll contracts approved. You're ready to trade.");
        }
        OutputFormat::Json => {
            println!("{}", serde_json::to_string_pretty(&results)?);
        }
    }

    Ok(())
}
